### ISSUE TITLE
/web failure: npm install fails

### ISSUE THREAD

**Issue by hesa** [hesa/coachassistant#10]
Following the instructions in web/README.md I get:
# npm install
npm WARN package.json coachassistant@0.0.0 No repository field.

Clean git clone
Ubuntu 15.04

**Comment by hesa** [comment]
Hmm, it seemed to work anyhow. Feel a bit stupid at the moment.

**Comment by jonkri** [comment]
Hi!

Oh, I have been confused about errors and warnings from npm too. :)

This particular warning just means that a reference to the Git repository is not present in the package description file. I think it's a good idea to add it.

**Comment by jonkri** [comment]
I think this should be fix now. :)
