### ISSUE TITLE
Wanted, changed order in json

### ISSUE THREAD

**Issue by hesa** [hesa/coachassistant#21]
It would be great if you could list name and uuid of "things" after each other.

**Comment by hesa** [comment]
Hacked my way around it ...

**Comment by jonkri** [comment]
What was the problem here? Did it have to do about the order of the properties in the JSON? If so, I don't think that JSON properties, semantically speaking, are supposed to be ordered.

**Comment by hesa** [comment]
I wanted to start writing Java code to read ... and used bash to write to db. Being the stupid idiot I am I reported an issue before thinking. After 2 minutes of bashing my populate script worked again.

Discard totally...
