### ISSUE TITLE
web  npm installation problems

### ISSUE THREAD

**Issue by hesa** [hesa/coachassistant#23]
npm install gives:

npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/home/hesa/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Linux 4.2.0-23-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/hesa
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /home/hesa/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/hesa/npm-debug.log
npm ERR! not ok code 0

----- and the log file:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install' ]
2 info using npm@1.4.21
3 info using node@v0.10.25
4 verbose config Skipping project config: /home/hesa/.npmrc. (matches userconfig
)
5 error install Couldn't read dependencies
6 error package.json ENOENT, open '/home/hesa/package.json'
6 error package.json This is most likely not a problem with npm itself.
6 error package.json npm can't find a package.json file in your current director
y.
7 error System Linux 4.2.0-23-generic
8 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
9 error cwd /home/hesa
10 error node -v v0.10.25
11 error npm -v 1.4.21
12 error path /home/hesa/package.json
13 error code ENOPACKAGEJSON
14 error errno 34
15 verbose exit [ 34, true ]

**Comment by jonkri** [comment]
Hi!

Thanks for this!

The problem here is that you need to change into the "web" directory in order for <code>npm install</code> to work, as it looks for the package.json file in the current directory. I have updated the web and server README files to include this information.
