### ISSUE TITLE
No ipv4 interface opened by docker

### ISSUE THREAD

**Issue by hesa** [hesa/coachassistant#26]
Probably my bad, but I ticket it anyway.

Having started up docker, I only find this:
tcp6       0      0 :::3000                 :::*                    LISTEN      29103/docker-proxy

Is there way to get an ipv4 interface up as well?

My system:
Ubuntu 15.10
ii  docker-compose 1.3.1-1      all          Punctual, lightweight development
ii  docker.io      1.6.2~dfsg1- amd64        Linux container runtime

**Comment by jonkri** [comment]
Perhaps a quick way to solve this in the short-term would be to disable IPv6 in Grub.

**Comment by hesa** [comment]
A reboot helped.

Will not close it until I know what caused it. Perhaps vbox fu*ed up the iptbles.

**Comment by jonkri** [comment]
Glad to hear it!

**Comment by hesa** [comment]
Has not happened again.
Closing issue
