### ISSUE TITLE
Menu/title in team and tp lists 

### ISSUE THREAD

**Issue by hesa** [hesa/coachassistant#36]

**Comment by hesa** [comment]
To make life a bit easier for users we shall provide a small title for each list in the separate fragments. I bet there is support for this in the currently used adapter

**Comment by jonkri** [comment]
Just to clarify: The convenience here relates to being able to quickly identify what is being displayed at the moment - for instance, teams, training phases or members.

**Comment by jonkri** [comment]
Is it currently the case that the title bar either displays the title of the activitity or a back button together with the name of the activity that we would go back to if we were to press the back button?

What's the status on this issue?

**Comment by hesa** [comment]
Solved when switching to Activity, and Actionbar, instead of Fragment.
