### ISSUE TITLE
Add small text in tp fragment to show team/tp

### ISSUE THREAD

**Issue by hesa** [hesa/coachassistant#37]

**Comment by jonkri** [comment]
When recording players, the user benefits from a reminder about what training phase is being recorded. While the team can be inferred from the list of members, it can of course be understood more conveniently with an explicit title.

**Comment by hesa** [comment]
I agree, but this is not easy to solve if we, at the same time, want a clean UI. 

Item for next meeting

**Comment by jonkri** [comment]
I agree. I think the optimal choice might be to show only the training phase.

**Comment by jonkri** [comment]
(Which of course helps the coaches avoid accidentally recording the video in the wrong training phase.)

**Comment by jonkri** [comment]
(Or maybe we can put the training phase in the new title bar?)

**Comment by jonkri** [comment]
Assigning myself so that I'll remember to bring this up for discussion.

**Comment by jonkri** [comment]
Superseded by #38.
