### ISSUE TITLE
Warn/Error if club name already exists

### ISSUE THREAD

**Issue by hesa** [hesa/coachassistant#4]
When adding a club with the same name more than once I think it would be better to warn (or error) the caller. Can't see any reason for allowing the same club name more than once?

/h

**Comment by jonkri** [comment]
Oh, absolutely. I also think that team and training phase names should be unique within a club. Do you agree?

**Comment by hesa** [comment]
Agree!

**Comment by jonkri** [comment]
As you can see above, I have added the relevant uniqueness constraints. However, the server will currently return a "500 Internal Server Error" when the uniqueness constraint is violated. It would be better if we had some appropriate exception handling in place and return something like "409 Conflict" instead. I will look into this before I close the issue.

**Comment by jonkri** [comment]
This is now fixed.

    $ curl --data '{ "name": "Bergsjö IF" }' --header "Content-Type: application/json" -v -request POST localhost:3000/0.0.0/clubs
    Warning: Invalid character is found in given range. A specified range MUST 
    Warning: have only digits in 'start'-'stop'. The server's response to this 
    Warning: request is uncertain.
    * Rebuilt URL to: POST/
    * Could not resolve host: POST
    * Closing connection 0
    curl: (6) Could not resolve host: POST
    *   Trying ::1...
    * Connected to localhost (::1) port 3000 (#1)
    > POST /0.0.0/clubs HTTP/1.1
    > Host: localhost:3000
    > Content-Range: bytes equest/25
    > User-Agent: curl/7.43.0
    > Accept: */*
    > Content-Type: application/json
    > Content-Length: 25
    > 
    * upload completely sent off: 25 out of 25 bytes
    < HTTP/1.1 409 Conflict
    < Transfer-Encoding: chunked
    < Date: Sun, 05 Jul 2015 17:29:06 GMT
    < Server: Warp/3.0.13
    < Content-Type: application/json; charset=UTF-8
    < 
    * Connection #1 to host localhost left intact
    {"customReason":{}}
