### ISSUE TITLE
Server installation problem

### ISSUE THREAD

**Issue by hesa** [hesa/coachassistant#42]
Trying to set up a server on a remote machine (at chalmers).

---- sys info ----

hesa@gesualdo:~/opt/coachassistant/server$ cat /etc/issue
Ubuntu 15.10 \n \l

Linux gesualdo 4.2.0-25-generic #30-Ubuntu SMP Mon Jan 18 12:31:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

docker-compose version: 1.3.1
CPython version: 2.7.10
OpenSSL version: OpenSSL 1.0.2d 9 Jul 2015

Docker version 1.6.2, build 7c8fca2

----

hesa@gesualdo:~/opt/coachassistant/server$ sudo docker-compose up
Recreating coachassistant_database_1...
Building server...
Step 0 : FROM haskell:7.8
 ---> 144fdf8d852d
Step 1 : RUN apt-get update
 ---> Using cache
 ---> 4cdc1e616ba3
Step 2 : RUN apt-get -y upgrade
 ---> Using cache
 ---> d0bfbc6ba938
Step 3 : RUN apt-get -y install libpq-dev netcat
 ---> Running in defb84860f07
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libpq-dev
E: Unable to locate package netcat
Service 'server' failed to build: The command [/bin/sh -c apt-get -y install libpq-dev netcat] returned a non-zero code: 100

**Comment by hesa** [comment]
Leaving Ubuntu. Trying with a clean Debian Jessie and Docker from their website.

docker-compose up works until...


update-alternatives: using /usr/lib/x86_64-linux-gnu/libtxc_dxtn_s2tc.so.0 to provide /usr/lib/x86_64-linux-gnu/libtxc_dxtn.so (libtxc-dxtn-x86_64-linux-gnu) in auto mode
Setting up dbus (1.8.20-0+deb8u1) ...
invoke-rc.d: policy-rc.d denied execution of start.
Setting up tcpd (7.6.q-25) ...
Setting up va-driver-all:amd64 (1.4.1-1) ...
Processing triggers for libc-bin (2.19-18+deb8u3) ...
Processing triggers for systemd (215-17+deb8u3) ...
 ---> a12c729becf7
Removing intermediate container be40a142f730
Step 6 : RUN cabal update
 ---> Running in d47e75ff6595
Config file path source is default config file.
Config file /root/.cabal/config not found.
Writing default configuration to /root/.cabal/config
Downloading the latest package list from hackage.haskell.org
 ---> 6c6b2267d5c2
Removing intermediate container d47e75ff6595
Step 7 : COPY ./lambdatrade-common /opt/dependencies/lambdatrade-common
 ---> 59dc682c6de5
Removing intermediate container a0411321d272
Step 8 : COPY coachassistant.cabal /opt/dependencies/coachassistant.cabal
 ---> f93f05bbab75
Removing intermediate container 79d7fca7b58c
Step 9 : COPY run.sh /app/run.sh
 ---> 0f89d6f9a464
Removing intermediate container adae729c01a8
Step 10 : RUN cd /opt/dependencies && cabal --ignore-sandbox install --only-dep . ./lambdatrade-common -j4 --force-reinstall
 ---> Running in 722ea2c12865
cabal: Error reading local package.
Couldn't find .cabal file in: ./lambdatrade-common
ERROR: Service 'server' failed to build: The command '/bin/sh -c cd /opt/dependencies && cabal --ignore-sandbox install --only-dep . ./lambdatrade-common -j4 --force-reinstall' returned a non-zero code: 1

**Comment by jonkri** [comment]
Ah, this one is easy. You just need to put the git submodules in place:

    git submodule init && git submodule update

This is in the Building section in the [server README](https://github.com/hesa/coachassistant/blob/master/server/README.md). Note that the following steps in the Building section are only relevant if you want to build outside of Docker (which I don't think you do).

**Comment by jonkri** [comment]
Since merging of the auth branch, you now need to run the <code>git submodule init && git submodule update</code> command in the root of the project.

**Comment by jonkri** [comment]
I added the above instructions to the root README file as part of the consolidation of the README files in b2309e1350ada2a54239d50980f954eb284e470a. I'm closing this issue - please re-open it if the problem remains.

**Comment by jonkri** [comment]
Sorry for the confusion - the instruction was already there. Anyway, it should be fixed.
