### ISSUE TITLE
IPv6 address to app server

### ISSUE THREAD

**Issue by jonkri** [hesa/coachassistant#45]
We decided to update the DNS to include an AAAA record to the app server.

@hesa: Can you see what the address is somewhere? If you let me know then I can update the DNS.

**Comment by hesa** [comment]
The server does not seem to have IPV6 enabled

**Comment by jonkri** [comment]
Aha, OK! Can you please confirm that ifconfig doesn't include an IPv6 address, and if that's the case, just close this issue? Thanks. :)

**Comment by hesa** [comment]
FUKE!!!! What was I using when I checked?

eth0      Link encap:Ethernet  HWaddr 00:22:15:bb:54:91  
          inet addr:129.16.213.216  Bcast:129.16.255.255  Mask:255.255.0.0
          inet6 addr: 2001:6b0:2:2f02:9d1a:66d4:7c04:d8e1/64 Scope:Global
          inet6 addr: fe80::222:15ff:febb:5491/64 Scope:Link
          inet6 addr: 2001:6b0:2:2f02:780d:5631:a717:5da3/64 Scope:Global
          inet6 addr: 2001:6b0:2:2f02:2175:cfd6:2022:19da/64 Scope:Global
          inet6 addr: 2001:6b0:2:2f02:d001:aefc:91fb:9caa/64 Scope:Global
          inet6 addr: 2001:6b0:2:2f02:a0c8:91d6:4be:fbc2/64 Scope:Global
          inet6 addr: 2001:6b0:2:2f02:f9f3:8f35:21e7:9207/64 Scope:Global
          inet6 addr: 2001:6b0:2:2f02:61e2:1013:c237:7f5e/64 Scope:Global
          inet6 addr: 2001:6b0:2:2f02:222:15ff:febb:5491/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:107993216 errors:0 dropped:0 overruns:0 frame:0
          TX packets:30783343 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:49263331474 (49.2 GB)  TX bytes:21811312497 (21.8 GB)

**Comment by hesa** [comment]
Nooooooooo, wrong machine. The missing ipv6 is still there... SRY!


eno1      Link encap:Ethernet  HWaddr 84:2b:2b:a8:b4:1a  
          inet addr:129.16.213.155  Bcast:129.16.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:55267039 errors:0 dropped:0 overruns:0 frame:0
          TX packets:12729838 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:19646173039 (19.6 GB)  TX bytes:9312857259 (9.3 GB)
          Interrupt:21 Memory:f7be0000-f7c00000

**Comment by jonkri** [comment]
Coolers! Thanks! I'll update the DNS when we get access to the DNS control panel again.

**Comment by jonkri** [comment]
I'll leave this assigned to you until we can access the DNS control panel.

I also understood your posts above as that we should point to 84:2b:2b:a8:b4:1a. Is that correct?

**Comment by hesa** [comment]
4:2b:2b:a8:b4:1a is a MAC address.

The server has no IPv6 support :(

**Comment by jonkri** [comment]
Ah, gotcha! I'll close this, then!
