### ISSUE TITLE
Forward 443 (or something; possibly also 80) to "app" VM

### ISSUE THREAD

**Issue by jonkri** [hesa/coachassistant#46]
In order to access the "app" area from the outside world, we will need to expose the 443/HTTPS port.

In the ideal case we would map 443 to 443 and 80 to 80. If we can't map from 80 on the host machine, then we don't need to map to 80 at all - it's just so that we can make a convenience redirect.

**Comment by hesa** [comment]
Working on it, but on the coachassistant server I get:

 telnet localhost 80
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

 telnet localhost 443
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

**Comment by hesa** [comment]
I am done forwarding (I hope). Have tested the ip tables with "netcat -l -p 443" faking a web server.

Jon, can you fire up the server

**Comment by jonkri** [comment]
Hi!

Thanks! I have started the app. The app can be started like this (I will add this along with other "DevOps" instructions to the README):

    $ docker start database
    $ docker start server
    $ docker start web

However, I get an error about a connection interruption when I visit the site:

https://app.tranarappen.se/

Perhaps the routing is problematic somehow. Are you sure you are specifying https and not http? Re-assign the issue to me if you want me to investigate more inside the VM.

**Comment by jonkri** [comment]
I edited the above issue slightly.

**Comment by hesa** [comment]
If I try to connect to 80 and 443 on the coachass server I get:

hesa@coachassistant:~$ telnet localhost 80
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

hesa@coachassistant:~$ telnet localhost 443
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

**Comment by hesa** [comment]
If I start netcat listening on 443 (sudo nc -l -p 443) I can do the following*:

  https://app.tranarappen.se/
  https://129.16.213.155/

Are you sure the web server is running on 80 and 443?

*) ... of course I get an error msg (unexpectedly closed the connection) but that's because netcat does not do ssl out of the box :)

**Comment by hesa** [comment]
port 3000 is also closed:

hesa@coachassistant:~$ telnet localhost 3000
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

**Comment by jonkri** [comment]
Thanks for that!

https://app.tranarappen.se/api/ now works (with self-signed certificate and browser exception, until we get a proper certificate). I had accidentally published the service onto random ports on 0.0.0.0.

I will make sure the web site works on / too.

**Comment by hesa** [comment]
Seems to be down:

hesa@coachassistant:~$ telnet localhost 3000
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

hesa@coachassistant:~$ telnet localhost 443
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

hesa@coachassistant:~$ telnet localhost 80
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

**Comment by jonkri** [comment]
No, I just restarted it. :)

**Comment by jonkri** [comment]
And now the web interface is up and running too. :)

**Comment by jonkri** [comment]
I see some JavaScript problems. I'll upload the old web build, with the prevously used dependencies.

**Comment by hesa** [comment]
Most important to me is to verify the API on port 3000

I plan to switch to using app.coac... instead of my local server.

**Comment by jonkri** [comment]
Hi! This is fixed now. I added the Docker instructions to https://github.com/hesa/coachassistant/commit/bb115ad61fba11da0c215ee9e981bbc204c7b1c7#diff-04c6e90faac2675aa89e2176d2eec7d8R38 - I think you may find them interesting.

The web app is running at https://app.tranarappen.se/. The API is running at https://app.tranarappen.se/api/.

**Comment by jonkri** [comment]
Hmm... Can't you switch the app to use HTTPS and port 443?

**Comment by jonkri** [comment]
If you can't use HTTPS, I think the solution would be to point 3000 to 3000 in the guest, and then proxy 3000 in the guest to the API, all without HTTPS. However, this would most likely be wasted effort in the sense that it would have to be thrown away as soon as we start using HTTPS.

**Comment by hesa** [comment]
https://app.tranarappen.se/api/0.0.0/clubs  :)

**Comment by hesa** [comment]
I'll try switching the app to https asap

**Comment by jonkri** [comment]
OK, great! Note that the SSL libraries will probably bark at the cert, so you will probably need to handle that somehow. Anyway, I'll assign this issue to you. Just forward 3000 on the host to 3000 in the guest and re-assign this issue to me in case you want us to do the HTTP thing I mentioned above.

**Comment by hesa** [comment]
3000 has been forwarded since at least a week :)

BUT, it seems a bit problematic to add SSL (with non good cert). Two options:

1) fallback to http - for a while
2) switch to new http classes in Android app. May take some days since I will be travelling for a week

**Comment by jonkri** [comment]
The first option is a lot easier, so I'm assuming that's the way to go. I'll fix this in just a moment.

**Comment by jonkri** [comment]
http://app.tranarappen.se:3000/0.0.0/clubs :)

**Comment by hesa** [comment]
Thanks!

... will read more about http over the travel.
