### ISSUE TITLE
Login functionality in the Android client

### ISSUE THREAD

**Issue by jonkri** [hesa/coachassistant#52]
Authentication will be verified by means of a token value.

This token value can be produced like so:

    POST /api/login
    { "user": "my_email@example.com", "password": "my_password" }

The response will, if the user name and password values are correct, include header "X-Token". It will also include the token in the JSON body like so:

    {"token":"the_token"}

These token values are identical, so you can access the one that is most convenient. (It also sets the token as a cookie, "token", but I doubt that this one is practical in this case.)

You will need to set this token value in future requests, such as with an "X-Token" header ("X-Token"), to access the application-specific API.

If an incorrect user name and password combination are provided, the endpoint will return 403.

This issue is currently blocked by #50.

**Comment by jonkri** [comment]
You will be able to Curl the token by doing this:

    curl -X POST -d '{"user":"my_email@example.com","password":"my_password"}' https://app.tranarappen.se/api/login

You can use <code>-v</code> to show the headers (the body of the response will be empty if the authentication request fails).

**Comment by jonkri** [comment]
This is now deployed. I have also sent your credentials and a token value to you.

**Comment by jonkri** [comment]
A Curl example on how to use the token would be

    curl -X POST -H 'X-Token: ...' https://app.tranarappen.se/api/logout

where <code>...</code> is the token value.

**Comment by hesa** [comment]
I get "HTTP/1.1 415 Unsupported Media Type"

See command below:

 curl -v -v -v -X POST -d '{"user":"hesa@sandklef.com","password":"password"}' https://app.tranarappen.se/api/login

=>

...
> POST /api/login HTTP/1.1
> User-Agent: curl/7.35.0
> Host: app.tranarappen.se
> Accept: */*
> Content-Length: 50
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 50 out of 50 bytes
< HTTP/1.1 415 Unsupported Media Type
* Server nginx/1.9.14 is not blacklisted
< Server: nginx/1.9.14
< Date: Sun, 24 Apr 2016 21:10:34 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< 
* Connection #0 to host app.tranarappen.se left intact

**Comment by jonkri** [comment]
Ah... The problem is this:

    Content-Type: application/x-www-form-urlencoded

Your request isn't encoded that way, as it's JSON. Sorry for not being explicit about this!

Add the following parameter to Curl, and it should work:

    -H 'Content-Type: application/json'

**Comment by hesa** [comment]
I like the way you rephrase "Henrik, you're an idiot" to"Sorry for not being explicit about this!"

Thanks. Works now. Will start hacking auth on the client tonite :)

**Comment by jonkri** [comment]
Ah, I have fallen into that trap too, so I guess we're both idiots in that case. :) Coolers!

**Comment by jonkri** [comment]
You were curious about the user-info endpoint. You can read about it here:

https://github.com/nejla/auth-service

Read from "A GET request to /api/user-info will"...
