### ISSUE TITLE
Delete, retake or reconfigure recorded member videos

### ISSUE THREAD

**Issue by jonkri** [hesa/coachassistant#55]
Some video recordings will be subject for deletion (possibly re-recording) or reconfirmation (change member) once recorded. By allowing for these actions, we shorten the time and resources necessary to process the uploaded batch of videos. This is at least for after 0.1.

**Comment by jonkri** [comment]
Change member is probably better to do in the web client.

**Comment by jonkri** [comment]
Not for the first iteration!

**Comment by jonkri** [comment]
A cancel button while recording might be a simple enough compromise. However, this is for post-0.1.

**Comment by hesa** [comment]
Being able to cancel the video recording in the Android app (as is currently possible) works. Also, we will be able to remove videos in the web UI.
