### ISSUE TITLE
Uploaded video does not show up on server

### ISSUE THREAD

**Issue by hesa** [hesa/coachassistant#58]
Currently testing the app* and just stumbled on a bug - most likely me but I give it to you in hope you can check the logs:

Today at around 12:13 I tried (and it seems it succeeded) uploading a video using the following URL:

https://app.tranarappen.se/api/0.0.0/clubs//f9d39cc2-cb7f-4ab0-b31a-5c0355596abe/videos/uuid/2c71a431-668e-4d81-8786-0506267771a6/upload

It is a small video (2-3 secs long) so the time to convert it should be short (I guess). It still can not be seen on the server (where I am logged in as hesa@sandklef.com using the club "AS Roma").

Can you check the logs to see the status of the video?

/h

*) some login bugs have been fixed :(

**Comment by jonkri** [comment]
Hey!

Visiting https://app.tranarappen.se/api/0.0.0/clubs/f9d39cc2-cb7f-4ab0-b31a-5c0355596abe/videos/uuid/2c71a431-668e-4d81-8786-0506267771a6 (which is basically the same URL that you posted, but without the upload bit) in the browser (that is, it's a GET request) shows the following:

    {"status":"complete","uuid":"2c71a431-668e-4d81-8786-0506267771a6","created":"2016-05-21T10:04:13.340029Z","published":"2016-05-21T10:14:29.212977Z","trainingPhaseUuid":"cd0910d3-d551-402d-b557-6cadac79e2a4","clubUuid":"f9d39cc2-cb7f-4ab0-b31a-5c0355596abe"}

I can also download the video here:

https://app.tranarappen.se/api/0.0.0/clubs/f9d39cc2-cb7f-4ab0-b31a-5c0355596abe/videos/uuid/2c71a431-668e-4d81-8786-0506267771a6

The reason why the video is not showing up in the web app is because the web app is not designed to play instructional videos.

Should we change this?

**Comment by jonkri** [comment]
(Updated download URL.)

**Comment by jonkri** [comment]
And just to clarify: The video is considered to be an instructional video since no member UUID is set.

**Comment by hesa** [comment]
Created this video:
---------------------------------------
{"status":"empty"
 "uuid":"5668f609-99de-43f1-9b81-fb0810ef89b7",
 "created":"2016-05-23T22:04:09.30128Z", 
 "trainingPhaseUuid":"cd0910d3-d551-402d-b557-6cadac79e2a4",
 "clubUuid":"f9d39cc2-cb7f-4ab0-b31a-5c0355596abe"}

Tried to upload it:
---------------------------------------
Upload media (file): /storage/emulated/0/com.sandklef.coachapp/f9d39cc2-cb7f-4ab0-b31a-5c0355596abe/new/20160524-000247.mp4
uuid    : 5668f609-99de-43f1-9b81-fb0810ef89b7
Upload server url: https://app.tranarappen.se/api/0.0.0/clubs//f9d39cc2-cb7f-4ab0-b31a-5c0355596abe/videos/uuid/5668f609-99de-43f1-9b81-fb0810ef89b7/upload

... seems to go well, I get ServerCode: 200

If I do
--------------------------
https://app.tranarappen.se/api/0.0.0/clubs//f9d39cc2-cb7f-4ab0-b31a-5c0355596abe/videos/uuid/5668f609-99de-43f1-9b81-fb0810ef89b7

I get the following:
{"status":"complete","uuid":"5668f609-99de-43f1-9b81-fb0810ef89b7","created":"2016-05-23T22:04:09.30128Z","published":"2016-05-23T22:06:10.194398Z","trainingPhaseUuid":"cd0910d3-d551-402d-b557-6cadac79e2a4","clubUuid":"f9d39cc2-cb7f-4ab0-b31a-5c0355596abe"}

**Comment by hesa** [comment]
Ah, ok. I missed that I had to tell which TP in the web frontend.

Sorry

**Comment by jonkri** [comment]
Ah, I see. Just let me know if you think the web UI needs to improve in this regard. Otherwise, let's consider this to be closed.
