### ISSUE TITLE
Disable synchronization button when there's no WiFi connection

### ISSUE THREAD

**Issue by jonkri** [hesa/coachassistant#68]
The synchronization button, which we might want to make available in the action bar in all activities, should be disabled when there's no access to WiFi. This is the only criteria for whether this button is active or not.

**Comment by hesa** [comment]
Fixed.

Wifi needed to sync, so when no wifi, sync button is diabled.

However, getting composite view is ok to do as long as we have network connectivity.

**Comment by jonkri** [comment]
I'm re-opening due to your last statement, so that we can discuss it.

<blockquote>However, getting data like the composite view is ok to do as long as we have some kind of network connectivity.</blockquote>

Should we allow composite syncing without media syncing, or do you think we can skip this for now?

**Comment by jonkri** [comment]
We decided that it didn't make sense to sync the composite and not the videos, since that would leave the app in an inconsistent state. Closing.
