### ISSUE TITLE
Show "recorded" timestamps rather than "created" timestamps

### ISSUE THREAD

**Issue by jonkri** [hesa/coachassistant#72]
There are three kinds of dates:

1. When the video was recorded
2. When the video was uploaded
3. When the video was published

1 is the most meaningful, and is the one that we want to display in the web application.

In order to support this, the video client has to publish the date value as an ISO string.

@hesa: Can you update the code that POSTs to /videos to include a "recorded" field that holds the date, in the same format as the dates you receive from the server? This way, the Android client won't break when I update the API.

I will update the API to <em>require</em> this value, migrate the database (setting "recorded" to "created"), and display the appropriate value in the web application.

This is optional for 0.1.

**Comment by hesa** [comment]
I assume you want this in the create POST?

**Comment by hesa** [comment]
Does look ok?

{ "trainingPhaseUuid": "c2c32f09-55e4-4a88-8592-46cf8e51cd5c" , "recorded": "2016-06-12T04:07:46.000000Z" , "memberUuid": "b9b9ebc6-e755-482d-ba8a-00911d0b69fa"}

**Comment by jonkri** [comment]
@hesa: Yes, that looks good! Please assign this issue to me when you're sending these dates in the create POST, like you described above.

**Comment by hesa** [comment]
The app sends this from now on.

**Comment by jonkri** [comment]
Thanks for that!

The server should now accept (require) this value.

@hesa, could you please check to see if it seems to work?

Also, if you need to migrate an existing database (I have already taken care of the beta instance), you just run the following SQL:

    ALTER TABLE video ADD recorded TIMESTAMP WITH TIME ZONE;
    UPDATE video SET recorded=created;
    ALTER TABLE video ALTER recorded SET NOT NULL;
