### ISSUE TITLE
Show name in addition to the timestamp in the web application

### ISSUE THREAD

**Issue by jonkri** [hesa/coachassistant#73]
Currently, videos are displayed only by when they are recorded. I should add the name of the member here.

**Comment by jonkri** [comment]
@hesa: This is done now!

**Comment by hesa** [comment]
It seems as if you always show the first name of the members in a team rather than the actual member in the video.

**Comment by jonkri** [comment]
This is now fixed, along with some other problems on the videos page!

Look at this newbie mistake:

https://github.com/hesa/coachassistant/commit/564ca7fd9c5adffa4de74f2bb3efe0a3a63d96cb#diff-f5c41dcfb6f32dbc4593b369ee6c5824R600

:)

**Comment by hesa** [comment]
Ha ha... Rikard and I discussed why = is a) used for assignment and b) equality check. These kinds of bugs should not be possibly to do ... I mean the language should not overload signs as they do.

How about x:=12;   (Pascal?)

**Comment by jonkri** [comment]
It's <code>=</code> for assignment in Haskell (where variables are not allowed), and <code>==</code> for equality check. <code>==</code> is simply a function, like any other, of type <code>Bool -> Bool -> Bool</code>.

Here is a top-level function definition:

    square x = x * 2

Here is assignment using the "let...in" syntax:

    main = let square x = x * 2 in putStrLn (show x)
