### ISSUE TITLE
Team ids in Member, Member ids in Team

### ISSUE THREAD

**Issue by hesa** [hesa/coachassistant#8]
We discussed over phone earlier today the idea of having UUID cross refs (e.g Member ref[] in Team. 

I am currently rewriting the json parser so it would be lovely to do it at the same time.

**Comment by jonkri** [comment]
@Philonous: Could you please provide some thoughts here? As you can see in the schema, each member can belong to zero or one teams. However, when we show the teams, we don't get the identifiers of their members. As it is now, I'm using <code>mkGenericJSON</code> to generate JSON instances for the entities. What @hesa is asking for above is to extend, for instance, the <code>Team</code> type to include a list field with the identifiers of <code>Member</code> entities currently assigned to that team, that is, making the one-to-many relationship between the two entities visible in "the other direction" of the JSON. The information itself is sort of redundant, but it would make the client code more convenient. Are there any shortcuts that I could take here, or should I create a new type with a <code>ToJson</code> instance from scratch? Thank you!

**Comment by Philonous** [comment]
You could either create a completely new type with all the fields, or you could try something like this:
```haskell
data WithMembers a =
  WithMembers{ withMembersMembers :: ![UUID]
             , withMembersBase :: !a
             } deriving (Show, Typeable, Data, Generic)

makeLensesWith camelCaseFields ''WithMembers

instance ToJSON a => ToJSON (WithMembers a) where
    toJSON wm = case toJSON (wm ^. base) of
                 Object o -> Object (o <> HashMap.singleton "members"
                                               (toJSON $ wm ^. members))
                 v -> object [ "base" .= v
                             , "members" .= (wm ^. members)
                             ]

instance JSONSchema a => JSONSchema (WithMembers a) where
    schema prx = case schema (view base <$> prx) of
                  Object fs -> Object (fs ++ [Field "members" True
                                                (schema (Proxy :: Proxy [UUID]))])
                  s -> Object [ Field "members" True (schema (Proxy :: Proxy [UUID]))
                              , Field "base" True s
                              ]
```
So instead of returning the Team directly you'd return a (WithMembers Team). 

The advantage of this is that you don't need to convert back and forth between basically identical types. Also you can add member-fields to other types as well (With type-level strings this could actually be made generic, so you could add all sorts of fields, I haven't worked this out yet, though) 

So I think this is more elegant, but I haven't tried it myself yet because I came up with it only recently.
 
For the sql code you could use [array_agg](http://www.postgresql.org/docs/9.4/static/functions-aggregate.html) to accumulate the UUIDS and avoid multiple querries

**Comment by jonkri** [comment]
@Philonous: Thanks for that!

@hesa: The composite endpoint now includes the member identifiers. It looks like this:

```json
{
    "members": [{
        "uuid": "e5dd45ac-c16a-47f5-ade6-fc52896a6157",
        "name": "Henrik",
        "clubUuid": "ccd11959-4497-4d27-99b6-7467b2445809",
        "teamUuid": "53dc2154-63ca-43c6-8312-e145cf722bc5"
    }, {
        "uuid": "3b7836e1-a7e2-427e-9b88-1825201bfbe5",
        "name": "Jon",
        "clubUuid": "ccd11959-4497-4d27-99b6-7467b2445809",
        "teamUuid": "53dc2154-63ca-43c6-8312-e145cf722bc5"
    }],
    "teams": [{
        "uuid": "2c361475-4dc0-4c3e-9404-505280d7b52d",
        "members": [],
        "name": "F05",
        "clubUuid": "ccd11959-4497-4d27-99b6-7467b2445809"
    }, {
        "uuid": "53dc2154-63ca-43c6-8312-e145cf722bc5",
        "members": ["e5dd45ac-c16a-47f5-ade6-fc52896a6157", "3b7836e1-a7e2-427e-9b88-1825201bfbe5"],
        "name": "P05",
        "clubUuid": "ccd11959-4497-4d27-99b6-7467b2445809"
    }],
    "trainingPhases": [],
    "name": "Bergsjö IF"
}
```

I didn't extend the non-composite endpoint, as I don't think you're planning to use it, and I think it's OK that it's a bit more "low-level". Just re-open this ticket if you disagree. :)

**Comment by jonkri** [comment]
(We need to use Esqueleto for using SqlExpr and array_agg. If we use regular Persistent we have to query all rows and aggregate them manually. We may sometimes have to run multiple queries, i.e. for joins.)
